name: colonel_pos_65
description: CP Colonel POS 6.5 — aplikasi point of sale restoran.
publish_to: "none"
version: 6.5.0+2

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  excel: ^4.0.6
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  google_sign_in: ^7.2.0
  googleapis: ^15.0.0
  http: ^1.5.0
  cryptography: ^2.9.0
  share_plus: ^10.1.4
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  file_picker: ^10.3.6
  image_picker: ^1.1.2
  pdf: ^3.11.3
  printing: ^5.14.2
  audioplayers: ^6.1.0
  print_bluetooth_thermal: ^1.2.1
  esc_pos_utils_plus: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - lib/features/home/assistant_question_bank_v72.json
    - assets/images/cp_logo.png
    - assets/images/cp_pos_transaction.png
    - assets/images/cart_icon.png
    - assets/images/cart_icon.jpg
    - assets/images/menu_card_icon.jpg

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/images/cp_logo.png
